name: CI

on:
  push:
    branches-ignore: [main]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js@16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: yarn install
      - run: yarn run test-ci
        env:
          CI: true
      - run: yarn run lint
